use airportdbms;
-- task17
SELECT DISTINCT AIRPLANE.Pmodel, AIRPLANE.Reg_No
FROM AIRPLANE
LEFT JOIN OWNS ON AIRPLANE.Reg_No = OWNS.Reg_No
LEFT JOIN PLANE_SERVICE ON AIRPLANE.Reg_No = PLANE_SERVICE.Reg_No
WHERE OWNS.ssn IS NULL
AND PLANE_SERVICE.Service_ID IS NULL
OR AIRPLANE.Reg_No NOT IN (
    SELECT OWNS.Reg_No
    FROM OWNS
    JOIN CORPORATION ON OWNS.ssn = CORPORATION.Cssn
)
AND AIRPLANE.Reg_No NOT IN (
    SELECT WORKS_ON.Plan_regno
    FROM WORKS_ON
    JOIN EMPLOYEE ON WORKS_ON.Essn = EMPLOYEE.Essn
    WHERE EMPLOYEE.Eshift = 'Morning'
);
